name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src

    - name: Test with pytest
      run: |
        pip install pytest
        pytest

    - name: Generate Markdown
      run: |
        python3 markdownGenerater.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "nicholas.conterno@duke.edu"
        git config --global user.name "nicholasconterno"
        git add generated_markdown.md histogram.png
        git commit -m "Add generated markdown and histogram" || echo "No changes to commit"
        git push
